apiVersion: v1
kind: Service
metadata:
  name: weektwo-nodejs-client
spec:
  selector:
    app: weektwo-nodejs-client
  type: {{ .Values.service.type }}
  ports:
  - name: http
  - port: 3000
    targetPort: 3000