version: '3'

services:
  backend:
    build: 
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  # nginx:
  #   build: 
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   restarts: always
  #   ports:
  #     - "3500:80"
    