version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: adsesugh/laravel-react-app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/taskone.ini:/usr/local/etc/php/conf.d/taskone.ini
    networks:
      - taskone-network

  #Nginx Service
  webserver:
    image: nginx:1.23.2-alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - taskone-network

  #MySQL Service
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - taskone-network

#Docker Networks
networks:
  taskone-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
